---
title: "field_data_collection_tracker"
author: "REACH"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile), '/livelihoods_field_data_collection_tracker_', format(Sys.Date(), '%Y_%m_%d'),'.html')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

# read packages
library(tidyverse)
library(lubridate)
library(glue)
library(leaflet)

df_refugee_samples <- readr::read_csv("../inputs/Refugee_livelihoods_survey_samples_definition.csv")
  
  
df_for_colnames <- df_refugee_samples %>% 
  mutate(location_type = str_to_lower(type),
         location_type = str_replace_all(string = location_type, pattern = " ", replacement = "_"),
         location = str_to_lower(location))%>% 
  select(location_type, location) %>% 
  unique()

df_refugee_samples_required <- df_refugee_samples %>% 
  select(location, sample_size) %>% 
  mutate(location = str_to_lower(location))

df_host_samples <- readr::read_csv("../inputs/Host_community_livelihoods_survey_samples_definition.csv")

df_for_host_colnames <- df_host_samples %>% 
  mutate(location_type = str_to_lower(type),
         location_type = str_replace_all(string = location_type, pattern = " ", replacement = "_"),
         location = str_to_lower(location))%>% 
  select(location_type, location) %>% 
  unique()
  

df_host_samples_required <- df_refugee_samples %>% 
  select(location, sample_size) %>% 
  mutate(location = str_to_lower(location))

df_tool_data <- readxl::read_excel("../inputs/livelihoods_assessment_data.xlsx") %>% 
  mutate(uuid = `_uuid`,
         start_date = as_date(start),
         start = as_datetime(start),
         end = as_datetime(end),
         latitude = as.numeric(`_geopoint_latitude`),
         longitude = as.numeric(`_geopoint_longitude`),
         location = str_to_lower(location)) %>% 
  filter(consent_two == "yes",  hoh_equivalent == "yes", respondent_age >= 18,
         start_date > as_date("2022-08-10"), 
         !str_detect(string = point_number, pattern = fixed('test', ignore_case = TRUE))
  ) %>% 
  mutate(
    location_type = ifelse(location == "kampala" & status == "refugee", location, refugee_settlement))

# days that contain data
df_days_for_data_collection <- df_tool_data %>% select(start_date) %>% unique() %>% arrange(start_date) %>% pull()

df_data_support_cl_log <- df_tool_data %>% 
  select(uuid, status,	location, latitude,	longitude )
# cleaning log handling
df_cl_log <- read_csv(file = "../inputs/combined_checks_livelihood.csv") %>% 
  mutate(adjust_log = ifelse(is.na(adjust_log), "apply_suggested_change", adjust_log)) %>% 
  left_join(df_data_support_cl_log, by = "uuid")

# change_response logs that affect stats in the data collection progress
cl_log_change_response <- df_cl_log %>% 
  filter(type == "change_response", 
         !is.na(value),
         reviewed == 1, 
         adjust_log != "delete_log", 
        ) %>% 
  select(uuid, name, value)

# updated tool data
df_updated_tool_data <- df_tool_data

# get uuids from cleaning log
uuids_chg_response <- cl_log_change_response %>% pull(uuid) %>% unique()

for (current_uuid in uuids_chg_response) {
  current_uuid_data <- cl_log_change_response %>% 
    filter(uuid == current_uuid) %>% 
    mutate(value = ifelse(name == "enumerator_id", as.numeric(value), value)) %>% 
    pivot_wider(names_from = "name", values_from = "value", uuid)
  print(current_uuid_data)
  # process current updates
  df_current_updated <- df_updated_tool_data %>% 
    rows_update(y = current_uuid_data, by = "uuid")
  # update the parent dataset with current updates
  df_updated_tool_data <- df_current_updated
}

# enumerator performance data
df_enum_performance <- df_updated_tool_data %>% 
  mutate(int.survey_time_interval = lubridate::time_length(end - start, unit = "min"),
         int.survey_time_interval = ceiling(int.survey_time_interval))

# functions for changing some options in the table
dt_set_options<- function(x){
  DT::datatable(x,
                options = list(
                  autoWidth=F,
                  dom= 't',
                  list(list(width = '20%', targets = list(1,2,3,4,5)))
                )
  )
}

dt_with_modified_options <- function(x){
  DT::datatable(x,
                rownames = FALSE,
                options = list(
                  columnDefs = list(list(className = 'dt-center', targets = list(1,2,3,4,5))),
                  pageLength = 20,
                  initComplete = JS(
                    "function(settings, json) {",
                    "$(this.api().table().header()).css({'background-color': '#333', 'color': '#fff'});",
                    "}")
                )
  )
}

dt_options_fewcols <- function(x){
  DT::datatable(x,
                rownames = FALSE,
                options = list(
                  pageLength = 20,
                  initComplete = JS(
                    "function(settings, json) {",
                    "$(this.api().table().header()).css({'background-color': '#333', 'color': '#fff'});",
                    "}")
                )
  )
}


dt_enum_performance_options <- function(x){
  DT::datatable(x,
                rownames = FALSE,
                filter = 'top',
                options = list(
                  columnDefs = list(list(className = 'dt-center', targets = list(1,2))),
                  pageLength = 50,
                  initComplete = JS(
                    "function(settings, json) {",
                    "$(this.api().table().header()).css({'background-color': '#333', 'color': '#fff'});",
                    "}"),
                  order = list(list(1, 'desc'), list(0, 'asc'), list(3, 'desc'))
                )
  )
}
```

## Summary on the surveys done

>There are **`r nrow(df_updated_tool_data)`** total number of surveys done as of **`r df_days_for_data_collection[length(df_days_for_data_collection)]`**.

### Settlements:  **`r df_updated_tool_data %>% filter(status == "refugee") %>% nrow()`** surveys

```{r, echo = FALSE}
df_refugee_samp_per_settlement <- df_refugee_samples_required %>% 
  group_by(location) %>% 
  summarise(required_samples = sum(sample_size, na.rm = TRUE))

df_cl_surveys_for_deletion <- df_cl_log %>% 
  filter(status == "refugee", type == "remove_survey", reviewed == 1, adjust_log != "delete_log") %>%
  group_by(location) %>% 
  distinct(uuid) %>%
  summarise(surveys_for_deletion = n())

df_updated_tool_data %>% 
  filter(status == "refugee") %>% 
  group_by(location_type, location) %>% 
  summarise(number_of_surveys = n()) %>% 
  arrange(location_type) %>% 
  right_join(df_refugee_samp_per_settlement, by = "location") %>% 
  left_join(df_cl_surveys_for_deletion, by = "location") %>% 
  mutate(number_of_surveys = ifelse(is.na(number_of_surveys), 0, number_of_surveys),
         surveys_for_deletion = ifelse(is.na(surveys_for_deletion), 0, surveys_for_deletion),
         int.surveys_and_deletion = number_of_surveys - surveys_for_deletion,
         remaining_surveys = required_samples - int.surveys_and_deletion ) %>% 
  left_join(df_for_colnames, by = "location") %>% 
  rename(location_type = location_type.x) %>%
  mutate(location_type = location_type.y) %>%
  select(-c(int.surveys_and_deletion, location_type.y)) %>% 
  dt_with_modified_options()
```

### Host community: **`r df_updated_tool_data %>% filter(status == "host_community") %>% nrow()`** surveys

```{r, echo = FALSE}
df_host_samp_per_location <- df_host_samples_required %>% 
  group_by(location) %>% 
  summarise(required_samples = sum(sample_size, na.rm = TRUE))

df_cl_surveys_for_deletion <- df_cl_log %>% 
  filter(status == "host_community", type == "remove_survey", reviewed == 1, adjust_log != "delete_log") %>%
  group_by(location) %>% 
  distinct(uuid) %>%
  summarise(surveys_for_deletion = n())

df_updated_tool_data %>% 
  filter(status == "host_community") %>% 
  group_by(location_type, location) %>% 
  summarise(number_of_surveys = n()) %>% 
  arrange(location_type) %>% 
  right_join(df_host_samp_per_location, by = "location") %>% 
  left_join(df_cl_surveys_for_deletion, by = "location") %>% 
  mutate(number_of_surveys = ifelse(is.na(number_of_surveys), 0, number_of_surveys),
         surveys_for_deletion = ifelse(is.na(surveys_for_deletion), 0, surveys_for_deletion),
         int.surveys_and_deletion = number_of_surveys - surveys_for_deletion,
         remaining_surveys = required_samples - int.surveys_and_deletion ) %>% 
  left_join(df_for_host_colnames, by = "location") %>% 
  rename(location_type = location_type.x) %>%
  mutate(location_type = location_type.y) %>%
  select(-c(int.surveys_and_deletion, location_type.y)) %>% 
  dt_with_modified_options()

```

```{r, echo = FALSE}
```